[workspace]
name = "FreeCAD"
version = "26.3.0"
description = "pixi instructions for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = [ "linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64" ]
requires-pixi = ">=0.60"

[dependencies]
av = "*"
blinker = "*"
calculix = "*"
ccache = "*"
cmake = "*"
compilers = "*"
conda-devenv = "*"
debugpy = "*"
defusedxml = "*"
docutils = "*"
doxygen = "*"
eigen = "*"
expat = "*"
fmt = "*"
freetype = "*"
git = "*"
graphviz = "*"
gtest= "*"
harfbuzz = "*"
hdf5 = "*"
ifcopenshell = "*"
lark = "*"
libboost-devel = "*"
lxml = "*"
matplotlib = "*"
netgen = "*"
nine = "*"
ninja = "*"
noqt5 = "*"
numpy = "*"
nlohmann_json = "*"
occt = ">=7.9,<8.0"
opencamlib = "*"
openssl = "*"
pandas = "*"
pcl = "*"
pip = "*"
ply = "*"
pre-commit = "*"
pyright = "*"
pybind11 = "*"
pycollada = "*"
pyside6 = "*"
python = ">=3.13,<3.14"
pythonocc-core = "*"
pyyaml = "*"
qt6-main = ">=6.11,<6.12"
requests = "*"
scipy = "*"
six = "*"
smesh = "*"
swig = "*"
sympy = "*"
typing-extensions = "*"
tbb-devel = "*"
vtk = "*"
xerces-c = "*"
xlutils = "*"
yaml-cpp = "*"
zlib = "*"
zstd = "*"
compiler-rt = "*"

## Linux Dependencies (x86-64)
[target.linux-64.dependencies]
clang = "*"
clangxx = "*"
kernel-headers_linux-64 = "*"
libdrm-conda-x86_64 = "*"
libopengl-devel = "*"
libselinux-conda-x86_64 = "*"
libsepol-conda-x86_64 = "*"
libspnav = "*"
libx11-common-conda-x86_64 = "*"
libx11-conda-x86_64 = "*"
libxau-conda-x86_64 = "*"
libxcb-conda-x86_64 = "*"
libxdamage-conda-x86_64 = "*"
libxext-conda-x86_64 = "*"
libxfixes-conda-x86_64 = "*"
libxi-conda-x86_64 = "*"
libxi-devel-conda-x86_64 = "*"
libxxf86vm-conda-x86_64 = "*"
llvm-openmp = "*"
mesa-dri-drivers-conda-x86_64 = "*"
mesa-libegl-conda-x86_64 = "*"
mesa-libegl-devel-conda-x86_64 = "*"
mesa-libgl-conda-x86_64 = "*"
mesa-libgl-devel-conda-x86_64 = "*"
mesa-libglu-devel-conda-x86_64 = "*"
mold = "*"
pixman-conda-x86_64 = "*"
qt6-wayland = "*"
sed = "*"
sysroot_linux-64 = "*"
xorg-x11-server-common-conda-x86_64 = "*"
xorg-x11-server-xvfb-conda-x86_64 = "*"
xorg-xproto = "*"

## Linux Dependencies (aarch64)
[target.linux-aarch64.dependencies]
clang = "*"
clangxx = "*"
kernel-headers_linux-aarch64 = "*"
libdrm-conda-aarch64 = "*"
libglvnd-conda-aarch64 = "*"
libglvnd-glx-conda-aarch64 = "*"
libopengl-devel = "*"
libselinux-conda-aarch64 = "*"
libsepol-conda-aarch64 = "*"
libspnav = "*"
libx11-common-conda-aarch64 = "*"
libx11-conda-aarch64 = "*"
libxau-conda-aarch64 = "*"
libxcb-conda-aarch64 = "*"
libxdamage-conda-aarch64 = "*"
libxext-conda-aarch64 = "*"
libxfixes-conda-aarch64 = "*"
libxi-conda-aarch64 = "*"
libxi-devel-conda-aarch64 = "*"
libxxf86vm-conda-aarch64 = "*"
llvm-openmp = "*"
mesa-dri-drivers-conda-aarch64 = "*"
mesa-khr-devel-conda-aarch64 = "*"
mesa-libegl-conda-aarch64 = "*"
mesa-libegl-devel-conda-aarch64 = "*"
mesa-libgbm-conda-aarch64 = "*"
mesa-libgl-conda-aarch64 = "*"
mesa-libgl-devel-conda-aarch64 = "*"
mesa-libglapi-conda-aarch64 = "*"
mold = "*"
pixman-conda-aarch64 = "*"
qt6-wayland = "*"
sed = "*"
sysroot_linux-aarch64 = "*"
xorg-x11-server-common-conda-aarch64 = "*"
xorg-x11-server-xvfb-conda-aarch64 = "*"
xorg-xproto = "*"

## macOS Dependencies (Intel)
[target.osx-64.dependencies]
sed = "*"

## macOS Dependencies (Apple Silicon)
[target.osx-arm64.dependencies]
sed = "*"

[target.win-64.dependencies]
libwinpthread = "*"

[pypi-dependencies]
freecad-stubs = "*"

## Qt 6 Configuration Presets
[target.linux-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-linux-debug", "{{ extra_args }}" ], args = [{ "arg" ="extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-linux-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.linux-aarch64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-linux-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on= ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-linux-release" ], depends-on= ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.osx-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-macos-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-macos-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.osx-arm64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-macos-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-macos-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.win-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-windows-debug", "-DCMAKE_GENERATOR_PLATFORM=", "-DCMAKE_GENERATOR_TOOLSET=", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-windows-release", "-DCMAKE_GENERATOR_PLATFORM=", "-DCMAKE_GENERATOR_TOOLSET=" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
freecad-debug = { cmd = [ ".pixi/envs/default/Library/bin/FreeCAD.exe" ], depends-on = ["install-debug"]}
freecad-release = { cmd = [ ".pixi/envs/default/Library/bin/FreeCAD.exe" ], depends-on = ["install-release"]}

[tasks]
initialize = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
# redirect to debug by default
configure = [{ task = "configure-debug" }]
build = [{ task = "build-debug" }]
install = [{ task = "install-debug" }]
test = [{ task = "test-debug" }]
freecad = [{ task = "freecad-debug" }]

build-debug = { cmd = ["cmake", "--build", "build/debug"]}
build-release = { cmd = ["cmake", "--build", "build/release"]}
install-debug = { cmd = ["cmake", "--install", "build/debug"]}
install-release = { cmd = ["cmake", "--install", "build/release"]}
test-debug = { cmd = ["ctest", "--test-dir", "build/debug"]}
test-release = { cmd = ["ctest", "--test-dir", "build/release"]}
freecad-debug = "build/debug/bin/FreeCAD"
freecad-release = "build/release/bin/FreeCAD"
