[workspace]
name = "FreeCAD"
description = "pixi instructions for FreeCAD"
authors = ["looooo <sppedflyer@gmail.com>"]
channels = ["conda-forge"]
platforms = [ "linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64" ]
requires-pixi = ">=0.48"

[dependencies]
blinker = "*"
calculix = "*"
ccache = "*"
cmake = "*"
coin3d = "*"
compilers = ">=1.11,<1.12"
conda-devenv = "*"
debugpy = "*"
defusedxml = "*"
docutils = "*"
doxygen = "*"
eigen = ">=3.4,<5"
fmt = "*"
freetype = "*"
git = "*"
graphviz = "*"
harfbuzz = "*"
hdf5 = "*"
ifcopenshell = "*"
lark = "*"
libboost-devel = "*"
liblzma-devel = "*"
libtiff = "*"
libvulkan-headers = "*"
lxml = "*"
matplotlib = "*"
netgen = "*"
nine = "*"
ninja = "*"
noqt5 = "*"
numpy = ">=2.3,<2.4"
occt = ">=7.9,<8.0"
opencamlib = "*"
opencv = "*"
openssl = "*"
pandas = "*"
pcl = "*"
pip = "*"
pivy = "*"
ply = "*"
pre-commit = "*"
pybind11 = "*"
pycollada = "*"
pyside6 = "*"
python = ">=3.13,<3.14"
pythonocc-core = "*"
pyyaml = "*"
qt6-main = ">=6.10,<6.11"
requests = "*"
scipy = "*"
six = "*"
smesh = "*"
swig = "*"
sympy = "*"
tbb-devel = "*"
vtk = "*"
xerces-c = "*"
xlutils = "*"
yaml-cpp = "*"
zlib = "*"
zstd = "*"
compiler-rt = ">=18.1.8,<22"

## Linux Dependencies (x86-64)
[target.linux-64.dependencies]
clang = "*"
clangxx = "*"
libgl-devel = "*"
libegl-devel = "*"
dbus = "*"
fontconfig = "*"
libxml2-devel = "*"
libxkbcommon = "*"
libxcb = "*"
libdrm = "*"
libcups = "*"
alsa-lib = "*"
wayland = "*"
xcb-util = "*"
xcb-util-wm = "*"
xcb-util-keysyms = "*"
xcb-util-image = "*"
xcb-util-renderutil = "*"
xcb-util-cursor = "*"
xorg-libx11 = "*"
xorg-libxau = "*"
xorg-libxext = "*"
xorg-libxfixes = "*"
xorg-libxdamage = "*"
xorg-libxi = "*"
xorg-libxrandr = "*"
xorg-libxcomposite = "*"
xorg-libxcursor = "*"
xorg-libsm = "*"
xorg-libice = "*"
xorg-libxxf86vm = "*"
xorg-libxtst = "*"
xorg-xorgproto = "*"
libspnav = "*"
llvm-openmp = "*"
mold = "*"
qt6-wayland = "*"
sed = "*"
xorg-x11-server-xvfb-conda-x86_64 = "*"

## Linux Dependencies (aarch64)
[target.linux-aarch64.dependencies]
clang = "*"
clangxx = "*"
libgl-devel = "*"
libegl-devel = "*"
dbus = "*"
fontconfig = "*"
libxml2-devel = "*"
libxkbcommon = "*"
libxcb = "*"
libdrm = "*"
libcups = "*"
alsa-lib = "*"
wayland = "*"
xcb-util = "*"
xcb-util-wm = "*"
xcb-util-keysyms = "*"
xcb-util-image = "*"
xcb-util-renderutil = "*"
xcb-util-cursor = "*"
xorg-libx11 = "*"
xorg-libxau = "*"
xorg-libxext = "*"
xorg-libxfixes = "*"
xorg-libxdamage = "*"
xorg-libxi = "*"
xorg-libxrandr = "*"
xorg-libxcomposite = "*"
xorg-libxcursor = "*"
xorg-libsm = "*"
xorg-libice = "*"
xorg-libxxf86vm = "*"
xorg-libxtst = "*"
xorg-xorgproto = "*"
libspnav = "*"
llvm-openmp = "*"
mold = "*"
qt6-wayland = "*"
sed = "*"
xorg-x11-server-xvfb-conda-aarch64 = "*"

## macOS Dependencies (Intel)
[target.osx-64.dependencies]
sed = "*"

## macOS Dependencies (Apple Silicon)
[target.osx-arm64.dependencies]
sed = "*"

[target.win-64.dependencies]
winpthreads-devel = "*"

[pypi-dependencies]
freecad-stubs = "*"

## Qt 6 Configuration Presets
[target.linux-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-linux-debug", "{{ extra_args }}" ], args = [{ "arg" ="extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-linux-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.linux-aarch64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-linux-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on= ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-linux-release" ], depends-on= ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.osx-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-macos-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-macos-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.osx-arm64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-macos-debug", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-macos-release" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}

[target.win-64.tasks]
configure-debug = { cmd = [ "cmake", "--preset", "conda-windows-debug", "-DCMAKE_GENERATOR_PLATFORM=", "-DCMAKE_GENERATOR_TOOLSET=", "{{ extra_args }}" ], args = [{ "arg" = "extra_args", "default" = "" }], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
configure-release = { cmd = [ "cmake", "--preset", "conda-windows-release", "-DCMAKE_GENERATOR_PLATFORM=", "-DCMAKE_GENERATOR_TOOLSET=" ], depends-on = ["initialize"], env={ CFLAGS="", CXXFLAGS="", DEBUG_CFLAGS="", DEBUG_CXXFLAGS="" }}
freecad-debug = { cmd = [ ".pixi/envs/default/Library/bin/FreeCAD.exe" ], depends-on = ["install-debug"]}
freecad-release = { cmd = [ ".pixi/envs/default/Library/bin/FreeCAD.exe" ], depends-on = ["install-release"]}

[tasks]
initialize = { cmd = ["git", "submodule", "update", "--init", "--recursive"]}
# redirect to debug by default
configure = [{ task = "configure-debug" }]
build = [{ task = "build-debug" }]
install = [{ task = "install-debug" }]
test = [{ task = "test-debug" }]
freecad = [{ task = "freecad-debug" }]

build-debug = { cmd = ["cmake", "--build", "build/debug"]}
build-release = { cmd = ["cmake", "--build", "build/release"]}
install-debug = { cmd = ["cmake", "--install", "build/debug"]}
install-release = { cmd = ["cmake", "--install", "build/release"]}
test-debug = { cmd = ["ctest", "--test-dir", "build/debug"]}
test-release = { cmd = ["ctest", "--test-dir", "build/release"]}
freecad-debug = "build/debug/bin/FreeCAD"
freecad-release = "build/release/bin/FreeCAD"
