context:
  version: "1.2.0dev"

package:
  name: freecad
  version: "${{ version }}"

source:
  path: ../..
  use_gitignore: true

build:
  number: 0

requirements:
  build:
    - ccache
    - cmake
    - compilers>=1.11,<1.12
    - doxygen
    - ninja
    - noqt5
    - python>=3.13,<3.14
    - qt6-main>=6.10,<6.11
    - swig>=4.4,<4.5

    - if: linux
      then:
        - clang
        - clangxx
        - libgl-devel
        - libegl-devel
        - dbus
        - fontconfig
        - libxml2-devel
        - libxkbcommon
        - libxcb
        - libdrm
        - libcups
        - alsa-lib
        - wayland
        - xcb-util
        - xcb-util-wm
        - xcb-util-keysyms
        - xcb-util-image
        - xcb-util-renderutil
        - xcb-util-cursor
        - xorg-libx11
        - xorg-libxau
        - xorg-libxext
        - xorg-libxfixes
        - xorg-libxdamage
        - xorg-libxi
        - xorg-libxrandr
        - xorg-libxcomposite
        - xorg-libxcursor
        - xorg-libsm
        - xorg-libice
        - xorg-libxxf86vm
        - xorg-libxtst
        - xorg-xorgproto
        - xorg-xproto
        - libspnav
        - llvm-openmp
        - mold
        - qt6-wayland
        - sed

    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}

  host:
    - coin3d
    - eigen >=3.4,<5
    - fmt
    - freetype
    - hdf5
    - lark
    - libboost-devel
    - matplotlib-base
    - noqt5
    - numpy>=2.3,<2.4
    - occt>=7.9,<8.0
    - pcl
    - pivy
    - ply
    - pybind11
    - pyside6
    - python>=3.13,<3.14
    - qt6-main>=6.10,<6.11
    - smesh
    - vtk
    - xerces-c
    - yaml-cpp
    - zlib

    - if: win
      then:
        - winpthreads-devel
        - tbb-devel

    - if: unix
      then:
        - sed

    - if: linux
      then:
        - libspnav
        - xorg-xproto

  run:
    - blas * openblas*
    - blinker
    - calculix
    - debugpy
    - defusedxml
    - docutils
    - gmsh
    - graphviz
    - ifcopenshell
    - lark
    - lxml
    - matplotlib-base
    - nine
    - noqt5
    - numpy>=2.3,<2.4
    - occt>=7.9,<8.0
    - olefile
    - opencamlib
    - opencv
    - pandas
    - pip
    - pivy
    - ply
    - pycollada
    - pyside6
    - python>=3.13,<3.14
    - pythonocc-core
    - pyyaml
    - qt6-main>=6.10,<6.11
    - requests
    - scipy
    - sympy
    - typing_extensions
    - vtk
    - xlutils

    - if: linux
      then:
        - libspnav
        - qt6-wayland
